springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.coder.spring.swagger.controller
springdoc.swagger-ui.path=/coder-documentation
#springdoc.api-docs.path=/coder-api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

coder.openapi.dev-url=http://localhost:8080
coder.openapi.prod-url=https://coder-api.com